<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class DelegacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $delegaciones = [
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-1','nivel'=> 'PRIMARIAS','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-2','nivel'=> 'PRIMARIAS','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-3','nivel'=> 'PRIMARIAS','sede' => 'ACULTZINGO','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-4','nivel'=> 'PRIMARIAS','sede' => 'ALAMO','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-5','nivel'=> 'PRIMARIAS','sede' => 'ALTOTONGA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-6','nivel'=> 'PRIMARIAS','sede' => 'ALVARADO','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-7','nivel'=> 'PRIMARIAS','sede' => 'BOCA DEL RIO','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-8','nivel'=> 'PRIMARIAS','sede' => 'CARDEL','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-9','nivel'=> 'PRIMARIAS','sede' => 'CERRO AZUL','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-10','nivel'=> 'PRIMARIAS','sede' => 'CIUDAD MENDOZA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-11','nivel'=> 'PRIMARIAS','sede' => 'COATEPEC','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-12','nivel'=> 'FORANEAS','sede' => 'COATZACOALCOS','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-13','nivel'=> 'LOCALES','sede' => 'COATZACOALCOS','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-14','nivel'=> 'LOCALES','sede' => 'CORDOBA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-15','nivel'=> 'PRIMARIAS','sede' => 'COSAMALOAPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-16','nivel'=> 'PRIMARIAS','sede' => 'COSCOMATEPEC','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-17','nivel'=> 'PRIMARIAS','sede' => 'COSOLEACAQUE','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-18','nivel'=> 'PRIMARIAS','sede' => 'CHICONTEPEC','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-19','nivel'=> 'PRIMARIAS','sede' => 'CHONTLA','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-20','nivel'=> 'PRIMARIAS','sede' => 'EMILIANO ZAPATA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-21','nivel'=> 'PRIMARIAS','sede' => 'ESPINAL','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-22','nivel'=> 'PRIMARIAS','sede' => 'FORTIN','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-23','nivel'=> 'PRIMARIAS','sede' => 'HUATUSCO','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-24','nivel'=> 'PRIMARIAS','sede' => 'HUAYACOCOTLA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-25','nivel'=> 'PRIMARIAS','sede' => 'ISLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-26','nivel'=> 'PRIMARIAS','sede' => 'IXHUATLAN DE MADERO','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-27','nivel'=> 'PRIMARIAS','sede' => 'IXTACZOQUITLAN','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-28','nivel'=> 'PRIMARIAS','sede' => 'JESUS CARRANZA','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-29','nivel'=> 'PRIMARIAS','sede' => 'LERDO DE TEJADA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-30','nivel'=> 'PRIMARIAS','sede' => 'MARTINEZ DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-31','nivel'=> 'FORANEAS','sede' => 'MINATITLAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-32','nivel'=> 'LOCALES','sede' => 'MINATITLAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-33','nivel'=> 'PRIMARIAS','sede' => 'MISANTLA','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-34','nivel'=> 'PRIMARIAS','sede' => 'NAOLINCO','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-35','nivel'=> 'PRIMARIAS','sede' => 'NARANJOS','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-36','nivel'=> 'PRIMARIAS','sede' => 'OMEALCA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-37','nivel'=> 'PRIMARIAS','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-38','nivel'=> 'PRIMARIAS','sede' => 'OZULUAMA','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-39','nivel'=> 'PRIMARIAS','sede' => 'PANUCO','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-40','nivel'=> 'PRIMARIAS','sede' => 'PAPANTLA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-41','nivel'=> 'PREESCOLAR','sede' => 'SAN ANDRES TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-42','nivel'=> 'PRIMARIAS','sede' => 'PASO DEL MACHO','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-43','nivel'=> 'PRIMARIAS','sede' => 'PIEDRAS NEGRAS','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-44','nivel'=> 'PRIMARIAS','sede' => 'PLATON SANCHEZ','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-45','nivel'=> 'PRIMARIAS','sede' => 'PLAYA VICENTE','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-46','nivel'=> 'PRIMARIAS','sede' => 'POZA RICA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-47','nivel'=> 'PRIMARIAS','sede' => 'LAS VIGAS DE RAMIREZ','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-48','nivel'=> 'PRIMARIAS','sede' => 'SAN ANDRES TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-49','nivel'=> 'PRIMARIAS','sede' => 'SAYULA DE ALEMAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-50','nivel'=> 'PRIMARIAS','sede' => 'SOLEDAD DE DOBLADO','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-51','nivel'=> 'PRIMARIAS','sede' => 'TANTOYUCA','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-52','nivel'=> 'PRIMARIAS','sede' => 'TEMPOAL','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-53','nivel'=> 'PRIMARIAS','sede' => 'TEOCELO','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-54','nivel'=> 'PRIMARIAS','sede' => 'TEQUILA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-55','nivel'=> 'PRIMARIAS','sede' => 'SAN JUAN TEXHUACAN','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-56','nivel'=> 'PRIMARIAS','sede' => 'TIERRA BLANCA','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-57','nivel'=> 'PRIMARIAS','sede' => 'TUXPAN','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-58','nivel'=> 'PRIMARIAS','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-59','nivel'=> 'PREESCOLAR','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-60','nivel'=> 'PREESCOLAR','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-61','nivel'=> 'LOCALES','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-62','nivel'=> 'FORANEAS','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-63','nivel'=> 'PREESCOLAR','sede' => 'COSAMALOAPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-64','nivel'=> 'PREESCOLAR','sede' => 'CORDOBA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-65','nivel'=> 'PRIMARIAS','sede' => 'ZONGOLICA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-66','nivel'=> 'FORANEAS','sede' => 'CORDOBA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-67','nivel'=> 'PRIMARIAS','sede' => 'GUTIERREZ ZAMORA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-68','nivel'=> 'PRIMARIAS','sede' => 'SANTIAGO TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-69','nivel'=> 'PRIMARIAS','sede' => 'TIHUATLAN','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-70','nivel'=> 'PRIMARIAS','sede' => 'TRES VALLES','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-71','nivel'=> 'PRIMARIAS','sede' => 'BENITO JUAREZ','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-72','nivel'=> 'PRIMARIAS','sede' => 'PUEBLO VIEJO','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-73','nivel'=> 'PRIMARIAS','sede' => 'PASO DE OVEJAS','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-74','nivel'=> 'PRIMARIAS','sede' => 'TLAPACOYAN','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-75','nivel'=> 'PRIMARIAS','sede' => 'CARRIZAL','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-76','nivel'=> 'PRIMARIAS','sede' => 'TOTUTLA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-77','nivel'=> 'PRIMARIAS','sede' => 'JUCHIQUE DE FERRER','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-78','nivel'=> 'PREESCOLAR','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-79','nivel'=> 'PREESCOLAR','sede' => 'ALVARADO','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-80','nivel'=> 'PREESCOLAR','sede' => 'TUXPAN ','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-81','nivel'=> 'PREESCOLAR','sede' => 'COATEPEC','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-82','nivel'=> 'PREESCOLAR','sede' => 'MINATITLAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-83','nivel'=> 'PREESCOLAR','sede' => 'POZA RICA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-84','nivel'=> 'TECNICOS DOCENTES ADMINISTRATIVOS','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-85','nivel'=> 'PREESCOLAR','sede' => 'PAPANTLA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-86','nivel'=> 'EDUCACION ESPECIAL','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-87','nivel'=> 'PRIMARIAS','sede' => 'IXCATEPEC','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-88','nivel'=> 'PREESCOLAR','sede' => 'MARTINEZ DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-89','nivel'=> 'PREESCOLAR','sede' => 'ISLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-90','nivel'=> 'PREESCOLAR','sede' => 'TANTOYUCA','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-91','nivel'=> 'PREESCOLAR','sede' => 'PANUCO','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-92','nivel'=> 'ENSEÑANZAS MUSICALES','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-93','nivel'=> 'PRIMARIAS','sede' => 'VEGA DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-I-94','nivel'=> 'PRIMARIAS','sede' => 'TAMIAHUA ','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-1','nivel'=> 'NORMAL','sede' => 'ACECECA','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-2','nivel'=> 'BACHILLERATO ANTONIO MARIA DE RIVERA VESPERTINA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-3','nivel'=> 'BACHILLERATO  ARTICULO 3° DIURNA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-4','nivel'=> 'BACHILLERATOS MATUTINOS','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-5','nivel'=> 'TELEBACHILLERATO','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-6','nivel'=> 'ILUSTRE INSTITUTO VERACRUZANO','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-7','nivel'=> 'SECUNDARIA Y BACHILLERES','sede' => 'POZA RICA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-8','nivel'=> 'SECUNDARIA Y BACHILLERES','sede' => 'COSAMALOAPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-9','nivel'=> 'ESCUELA SECUNDARIA Y BACHILLERES DE ARTES Y OFICIOS','sede' => 'CORDOBA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-10','nivel'=> 'SECUNDARIA Y BACHILLERES','sede' => 'ALVARADO','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-11','nivel'=> 'SECUNDARIA','sede' => 'COATZACOALCOS','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-12','nivel'=> 'SECUNDARIA Y BACHILLERES','sede' => 'TLACOTALPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-13','nivel'=> 'NORMAL','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-14','nivel'=> 'ABIERTA','sede' => 'ALVARADO','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-15','nivel'=> 'BACHILLERATOS VESPERTINOS','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-16','nivel'=> 'TELEBACHILLERATO','sede' => 'SAN ANDRES TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-17','nivel'=> 'TELESECUNDARIA','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-18','nivel'=> 'TELEBACHILLERATO','sede' => 'CHICONTEPEC','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-19','nivel'=> 'TELEBACHILLERATO','sede' => 'ALAMO','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-20','nivel'=> 'TELEBACHILLERATO','sede' => 'TUXPAN','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-21','nivel'=> 'TELEBACHILLERATO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-22','nivel'=> 'TELEBACHILLERATO','sede' => 'NARANJOS','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-23','nivel'=> 'SECUNDARIA','sede' => 'COATZACOALCOS','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-24','nivel'=> 'UNIVERSIDAD PEDAGOGICA VERACRUZANA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-25','nivel'=> 'TELEBACHILLERATO','sede' => 'ESPINAL','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-26','nivel'=> 'TELEBACHILLERATO','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-27','nivel'=> 'TELEBACHILLERATO','sede' => 'TIERRA BLANCA','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-28','nivel'=> 'TELEBACHILLERATO','sede' => 'ISLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-29','nivel'=> 'NORMAL','sede' => 'TLACOTALPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-30','nivel'=> 'TELEBACHILLERATO','sede' => 'COSAMALOAPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-31','nivel'=> 'TELEBACHILLERATO','sede' => 'COSCOMATEPEC','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-32','nivel'=> 'TELEBACHILLERATO','sede' => 'MARTINEZ DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-33','nivel'=> 'TELEBACHILLERATO','sede' => 'POZA RICA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-34','nivel'=> 'TELEBACHILLERATO','sede' => 'MISANTLA','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-35','nivel'=> 'TELEBACHILLERATO','sede' => 'TANTOYUCA','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-36','nivel'=> 'SECUNDARIA Y BACHILLERES','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-37','nivel'=> 'TELESECUNDARIA','sede' => 'TANTOYUCA','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-38','nivel'=> 'TELESECUNDARIA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-39','nivel'=> 'TELESECUNDARIA','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-40','nivel'=> 'TELESECUNDARIA','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-41','nivel'=> 'TELESECUNDARIA','sede' => 'POZA RICA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-42','nivel'=> 'TELESECUNDARIA','sede' => 'MARTINEZ DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-43','nivel'=> 'BACHILLERATO','sede' => 'ALVARADO','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-44','nivel'=> 'TELEBACHILLERATO','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-45','nivel'=> 'TELEBACHILLERATO','sede' => 'COATZACOALCOS','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-46','nivel'=> 'TELEBACHILLERATO II','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-47','nivel'=> 'TELEBACHILLERATO','sede' => 'PAPANTLA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-48','nivel'=> 'TELEBACHILLERATO','sede' => 'SAN RAFAEL','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-49','nivel'=> 'SECUNDARIA','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-50','nivel'=> 'TELEBACHILLERATO','sede' => 'TEMPOAL','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-51','nivel'=> 'TELEBACHILLERATO','sede' => 'SANTIAGO TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-52','nivel'=> 'TELESECUNDARIA','sede' => 'COATZACOALCOS','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-53','nivel'=> 'ESCUELA SECUENDARIA Y BACHILLERATO ABIERTO','sede' => 'TUXPAN','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-54','nivel'=> 'TELESECUNDARIA','sede' => 'ALAMO','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-56','nivel'=> 'BACHILLERATO ANTONIO MARIA DE RIVERA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-57','nivel'=> 'TELEBACHILLERATO','sede' => 'HUAYACOCOTLA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-58','nivel'=> 'TELEBACHILLERATO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-II-59','nivel'=> 'SECUNDARIA GENERAL','sede' => 'PANUCO','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-1','nivel'=> 'MANUALES','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-2','nivel'=> 'EDUCACION FISICA','sede' => 'TIERRA BLANCA','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-3','nivel'=> 'ADMINISTRATIVOS OFICINAS CENTRALES','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-4','nivel'=> 'ADMINISTRATIVOS  EDUCACION FISICA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-5','nivel'=> 'EDUCACION FISICA','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-6','nivel'=> 'EDUCACION FISICA','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-7','nivel'=> 'EDUCACION FISICA','sede' => 'ALVARADO','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-8','nivel'=> 'ADMINISTRATIVOS Y DOCENTES DE LA D.G.B','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-9','nivel'=> 'ADMINISTRATIVOS TELEBACHILLERATO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-10','nivel'=> 'EDUCACION FISICA','sede' => 'CIUDAD MENDOZA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-11','nivel'=> 'EDUCACION FISICA','sede' => 'CORDOBA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-12','nivel'=> 'EDUCACION FISICA','sede' => 'POZA RICA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-13','nivel'=> 'EDUCACION FISICA','sede' => 'TUXPAN','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-14','nivel'=> 'DOCENTES EDUCACION FISICA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-15','nivel'=> 'EDUCACION FISICA','sede' => 'MARTINEZ DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-16','nivel'=> 'EDUCACION FISICA','sede' => 'COATEPEC','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-17','nivel'=> 'EDUCACION FISICA','sede' => 'TANTOYUCA','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-18','nivel'=> 'EDUCACION FISICA','sede' => 'CARDEL','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-19','nivel'=> 'EDUCACION FISICA','sede' => 'SAN ANDRES TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-20','nivel'=> 'EDUCACION FISICA','sede' => 'COSAMALOAPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-21','nivel'=> 'EDUCACION FISICA','sede' => 'HUATUSCO','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-22','nivel'=> 'EDUCACION FISICA','sede' => 'COATZACOALCOS','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-23','nivel'=> 'EDUCACION FISICA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-III-24','nivel'=> 'ADMINISTRATIVOS TELEBACHILLERATO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-1','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-2','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-3','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'SAN ANDRES TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-4','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'CIUDAD MENDOZA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-5','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'SOLEDAD DE DOBLADO','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-6','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'COSAMALOAPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-7','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-8','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'MARTINEZ DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-9','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'TUXPAN','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-10','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'POZA RICA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-11','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'TEMPOAL ','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-12','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'NARANJOS','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-13','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'TANTOYUCA','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-14','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'ALAMO','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-15','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'PAPANTLA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-16','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'CORDOBA','id_region' => '7'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-17','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'COATEPEC','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-18','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'ALTOTONGA','id_region' => '5'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-19','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'COATZACOALCOS','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-20','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-21','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'ALVARADO','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-22','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'CHICONTEPEC','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-23','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'PANUCO','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-24','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'GUTIERREZ ZAMORA','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-25','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'MINATITLAN','id_region' => '11'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-26','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'ISLA','id_region' => '10'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-27','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'BOCA DEL RIO','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-28','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'MISANTLA','id_region' => '4'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-29','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'TIERRA BLANCA','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-30','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'PIEDRAS NEGRAS','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-31','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'TIHUATLAN','id_region' => '3'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-32','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'ZONGOLICA','id_region' => '8'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-33','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'CARDEL','id_region' => '6'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-34','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'TLACOTALPAN','id_region' => '9'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-35','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'PUEBLO VIEJO','id_region' => '1'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-36','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'TAMIAHUA ','id_region' => '2'],
            ['nomenclatura'=>'delegacion', 'delegacion'=>'D-IV-37','nivel'=> 'JUBILADOS Y PENSIONADOS','sede' => 'PLATON SANCHEZ','id_region' => '1'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.01','nivel'=> 'BACHILLERATO','sede' => 'PAPANTLA','id_region' => '3'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.02','nivel'=> 'SECUNDARIA','sede' => 'HUATUSCO','id_region' => '7'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.03','nivel'=> 'BACHILLERATO SABATINO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.04','nivel'=> 'SECUNDARIA Y BACHILLERES','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.05','nivel'=> 'ESCUELA Y BACHILLERES ALFONSO REYES','sede' => 'MISANTLA','id_region' => '4'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.06','nivel'=> 'BACHILLERATO OFICIAL','sede' => 'CARDEL','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.07','nivel'=> 'SECUNDARIA GENERAL','sede' => 'IXCATEPEC','id_region' => '1'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.08','nivel'=> 'UNIVERSIDAD PEDAGOGICA VERACRUZANA','sede' => 'TUXPAN','id_region' => '2'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.09','nivel'=> 'SECUNDARIA GENERAL','sede' => 'SAN RAFAEL','id_region' => '4'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.10','nivel'=> 'SECUNDARIA','sede' => 'SOLEDAD DE DOBLADO','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.11','nivel'=> 'BACHILLERATO OFICIAL','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.13','nivel'=> 'SECUNDARIA','sede' => 'CIUDAD MENDOZA','id_region' => '8'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.14','nivel'=> 'BACHILLERATO','sede' => 'ORIZABA','id_region' => '8'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.15','nivel'=> 'BACHILLERATO NOCTURNA','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.17','nivel'=> 'UNIVERSIDAD FEMENINA','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.18','nivel'=> 'ESCUELA SECUNDARIA EXPERIMENTAL','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.20','nivel'=> 'BACHILLEARTO RICARDO FLORES MAGON MIXTO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.21','nivel'=> 'BACHILLERATO ANTONIO MARIA DE RIVERA MIXTA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.22','nivel'=> 'BACHILLERATO ESTEBAN MORALES','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.23','nivel'=> 'BACHILLERATO JOAQUIN RAMIREZ CABAÑAS MIXTA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.24','nivel'=> 'DEPARTAMENTO NORMALES','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.25','nivel'=> 'EDUCACION FISICA','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.26','nivel'=> 'ESCUELA DE ENFERMERIA','sede' => 'ACAYUCAN','id_region' => '11'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.27','nivel'=> 'BACHILLERATO EXPERIMENTAL MIXTA','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.29','nivel'=> 'BACHILLERATO','sede' => 'MARTINEZ DE LA TORRE','id_region' => '4'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.30','nivel'=> 'SECUNDARIA Y BACHILLERATO','sede' => 'MINATITLAN','id_region' => '11'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.31','nivel'=> 'UNIVERSIDAD PEDAGOGICA VERACRUZANA','sede' => 'VERACRUZ','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.32','nivel'=> 'SECUNDARIA','sede' => 'CARDEL','id_region' => '6'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.33','nivel'=> 'NORMAL MANUEL SUAREZ TRUJILLO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.35','nivel'=> 'TELEBACHILLERATO','sede' => 'XALAPA','id_region' => '5'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.36','nivel'=> 'SECUNDARIA Y BACHILLERATO','sede' => 'SANTIAGO TUXTLA','id_region' => '10'],
            ['nomenclatura'=>'centro de trabajo', 'delegacion'=>'C.T.40','nivel'=> 'TELEBACHILLERATO','sede' => 'ZONGOLICA','id_region' => '8'],


        ];
        DB::table(table:'delegaciones')->insert($delegaciones);
    }
}
